# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3e7eb65eafec8c12e04f6237ed6c93e9229d65efbf5373249c5a4f8f9261d64e812c9b38f72a0542875393e01bb2764ab3c1d90bf50f5fb53df46ab37159620

test:
  secret_key_base: f0693f005355aa1a528d1b89b3e98ba80d035b80fc2bcb4fc0264ab42949e88bdbdb38f282d095a64faff815c07fe597b70794f0da7437d871d7b8759668789c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
